### ISSUE TITLE
Assignment3

### ISSUE THREAD

**Issue by vkats-spbu** [Danil-Stenyashin/HomeAssignments#2]
Задание выполнено не до конца - используйте Google test

**Comment by AndreyIsakov01** [comment]
1) Необходимо 2 поля-объекта в базовом классе. При реализации советую обратить внимание на данный пример 
https://stackoverflow.com/questions/25779394/c-association-aggregation-and-composition
2) В Makefile реализовать цель test. Пример: 
https://github.com/vkats-spbu/gtest-demo/blob/main/Makefile
3) Последний релиз g-test требует С++ 14. Измените стандарт в Makefile
https://github.com/google/googletest?tab=readme-ov-file#release-1152
4) В наследуемых классах должно быть 2-3 поля с get-set методами
